name: Laravel CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Composer Dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --optimize-autoloader --no-progress --no-interaction

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test --filter=ExampleTest